name: Generate Dart Phone Location Maps

on:
  schedule:
    - cron: '0 12 15 * *' # Runs every month on the 15th at 12:00 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download SQL File
        run: wget https://github.com/dannyhu926/phone_location/raw/refs/heads/master/mysql/phone_location.sql -O phone_location.sql

      - name: Generate Dart Maps
        run: |
          awk -F'\t' '$0 ~ /^INSERT INTO/ { for (i=2; i<=NF; i++) { split($i, a, ","); phone = a[1]; province = a[2]; city = a[3]; printf "    86%s: \"%s%s\",\n", phone, province, city > zh.txt; printf "    86%s: \"%s, %s\",\n", phone, province, city > en.txt } }' phone_location.sql
          sed -i 's/^[^(]*(\([^)]*\)).*/\1/' zh.txt  # Remove extra characters
          sed -i 's/^[^(]*(\([^)]*\)).*/\1/' en.txt


      - name: Create Dart Files
        run: |
          cat << EOF > lib/phone_location_zh.dart
          Map<int, String> get86_zh() {
            return {
          $(cat zh.txt)
            };
          }
          EOF

          cat << EOF > lib/phone_location_en.dart
          Map<int, String> get86_en() {
            return {
          $(cat en.txt)
            };
          }
          EOF
          
      - name: Commit Dart Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Dart phone location maps"
          file_pattern: lib/phone_location_zh.dart lib/phone_location_en.dart
          branch: dartnumber
          repository: .
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          


      - name: Cleanup
        run: mysql -u root -e "DROP DATABASE temp_phone_location;"
