name: Convert SQL to CSV Generate reduced Dart Phone Location Maps

on:
  workflow_dispatch:
  schedule:
     - cron: '0 12 1 * *'
  
permissions:
  contents: write

jobs:
  convert-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dartnumber

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas and requests
        run: |
          python -m pip install --upgrade pip
          pip install requests pypinyin pandas

      - name: Download SQL and Convert to CSV
        run: |
          cat > convert_sql_to_csv.py << 'EOF'
          import requests
          import pandas as pd
          import csv

          def download_sql():
              url = "https://github.com/dannyhu926/phone_location/raw/refs/heads/master/mysql/phone_location.sql"
              response = requests.get(url)
              response.raise_for_status()
              return response.text

          def convert_to_csv(sql_content, csv_filepath):
              insert_statements = [line for line in sql_content.splitlines() if line.startswith("INSERT INTO `phone_location`")]
              data = []
              for statement in insert_statements:
                  values_str = statement[statement.find("VALUES") + len("VALUES"):].strip()
                  values = []
                  in_quote = False
                  current_value = ""
                  for char in values_str:
                      if char == "'":
                          in_quote = not in_quote
                      elif char == "," and not in_quote:
                          values.append(current_value.strip("'"))
                          current_value = ""
                      elif in_quote:
                          current_value += char
                  values.append(current_value.strip("'"))
                  data.append(values[1:5])

              df = pd.DataFrame(data, columns=['pref', 'phone', 'province', 'city'])
              df.to_csv(csv_filepath, index=False, quoting=csv.QUOTE_NONNUMERIC)

          if __name__ == "__main__":
              sql_content = download_sql()
              convert_to_csv(sql_content, 'phone_location.csv')
          EOF
          python convert_sql_to_csv.py

      - name: Commit and Push CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update phone_location"
          file_pattern: "phone_location.csv"
          branch: dartnumber
          repository: .
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}

      - name: Stage 2 Preprocess CSV
        run: |
          cat > preprocess_csv.py << 'EOF'
          import pandas as pd
          import csv

          df = pd.read_csv('phone_location.csv')
          df = df.drop(columns=['pref'])
          df['phone'] = '86' + df['phone'].astype(str).str.replace("'", "")
          df['province'] = df['province'].str.replace("'", "")
          df['city'] = df['city'].str.replace("'", "")
          df.to_csv('phone_location_processed.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)
          EOF
          python preprocess_csv.py

      - name: Stage 3 Generate Dart files
        run: |
          cat > generate_dart.py << 'EOF'
          import csv
          from pypinyin import lazy_pinyin, Style
          import os

          def convert_to_pinyin(province, city):
              p = ''.join(lazy_pinyin(province, style=Style.NORMAL))
              c = ''.join(lazy_pinyin(city, style=Style.NORMAL))
              return f"{c.title()}, {p.title()}"

          def process_csv_data(csv_filepath):
              zh_map = {}
              en_map = {}
              with open(csv_filepath, 'r', encoding='utf-8') as csvfile:
                  reader = csv.DictReader(csvfile)
                  for row in reader:
                      phone = row.get('phone')
                      province = row.get('province')
                      city = row.get('city')

                      if phone and province and city:
                          try:
                              phone_key = int(phone)
                          except ValueError as e:
                              print(f"Skipping record due to invalid phone: {phone}, error: {e}")
                              continue

                          zh_map[phone_key] = f"{province}{city}"
                          en_map[phone_key] = convert_to_pinyin(province, city)

              return zh_map, en_map

          def generate_dart_files(zh_map, en_map):
              os.makedirs('lib', exist_ok=True)

              with open('lib/phone_location_zh.dart', 'w', encoding='utf-8') as f:
                  f.write('// Generated by GitHub Actions\n')
                  f.write('// Source: https://github.com/dannyhu926/phone_location\n\n')
                  f.write('Map<int, String> get86_zh() {\n  return {\n')
                  for phone, location in zh_map.items():
                      f.write(f'    {phone}: "{location}",\n')
                  f.write('  };\n}\n')

              with open('lib/phone_location_en.dart', 'w', encoding='utf-8') as f:
                  f.write('// Generated by GitHub Actions\n')
                  f.write('// Source: https://github.com/dannyhu926/phone_location\n\n')
                  f.write('Map<int, String> get86_en() {\n  return {\n')
                  for phone, location in en_map.items():
                      f.write(f'    {phone}: "{location}",\n')
                  f.write('  };\n}\n')

          if __name__ == "__main__":
              zh_map, en_map = process_csv_data('phone_location_processed.csv')
              generate_dart_files(zh_map, en_map)
          EOF
          python generate_dart.py



      - name: Stage 4 Optimize Phone Ranges
        run: |
          cat > optimize_ranges.py << 'EOF'
          import pandas as pd
          from collections import defaultdict
          from pypinyin import lazy_pinyin, Style

          def convert_to_pinyin(province, city):
              p = ''.join(lazy_pinyin(province, style=Style.NORMAL))
              c = ''.join(lazy_pinyin(city, style=Style.NORMAL))
              return f"{c.title()}, {p.title()}"

          def find_consecutive_ranges(numbers):
              """查找末尾0-9连续且地址相同的号码组"""
              groups = defaultdict(list)
              for num in numbers:
                  prefix = num[:-1]
                  groups[prefix].append(num)

              consecutive_groups = []
              for prefix, group in groups.items():
                  if len(group) == 10:
                      sorted_group = sorted(group)
                      if all(n[-1] == str(i) for i, n in enumerate(sorted_group)):
                          consecutive_groups.append(sorted_group)
              return consecutive_groups

          def optimize_phone_ranges(input_file):
              # 第一轮：读取CSV
              df = pd.read_csv(input_file)
              phone_dict = {}
              for _, row in df.iterrows():
                  phone = str(row['phone'])
                  phone_dict[phone] = {'province': row['province'], 'city': row['city']}

              # 第一轮：处理连续范围
              processed = set()
              optimized = {}
              number_groups = defaultdict(list)
              for phone in phone_dict.keys():
                  info = phone_dict[phone]
                  number_groups[f"{info['province']}{info['city']}"].append(phone)

              for location, numbers in number_groups.items():
                  consecutive_groups = find_consecutive_ranges(numbers)
                  for group in consecutive_groups:
                      prefix = group[0][:-1]
                      if all(phone_dict[num]['province'] + phone_dict[num]['city'] == location for num in group):
                          optimized[int(prefix)] = phone_dict[group[0]]
                          processed.update(group)

              # 保存第一轮结果到临时字典
              temp_dict = {}
              for prefix, info in optimized.items():
                  temp_dict[str(prefix)] = info
              for phone, info in phone_dict.items():
                  if phone not in processed:
                      temp_dict[phone] = info

             # 第二轮：对第一轮结果再次处理
              processed = set()
              final_optimized = {}
              number_groups = defaultdict(list)
               for phone in temp_dict.keys():
                  info = temp_dict[phone]
                   number_groups[f"{info['province']}{info['city']}"].append(phone)

              for location, numbers in number_groups.items():
                  consecutive_groups = find_consecutive_ranges(numbers)
                  for group in consecutive_groups:
                      prefix = group[0][:-1]
                      if all(temp_dict[num]['province'] + temp_dict[num]['city'] == location for num in group):
                          final_optimized[int(prefix)] = temp_dict[group[0]]
                          processed.update(group)

              for phone, info in temp_dict.items():
                  if phone not in processed:
                      final_optimized[int(phone)] = info

              optimized_zh = {}
              optimized_en = {}
              for phone, info in final_optimized.items():
                  optimized_zh[phone] = f"{info['province']}{info['city']}"
                  optimized_en[phone] = convert_to_pinyin(info['province'], info['city'])

              return optimized_zh, optimized_en


          def generate_optimized_dart_files(optimized_zh, optimized_en):
                # 生成优化后的中文版本
              with open('lib/phone_location_zh_optimized.dart', 'w', encoding='utf-8') as f:
                  f.write('// Generated by GitHub Actions - Optimized Version\n')
                  f.write('// Source: https://github.com/dannyhu926/phone_location\n\n')
                  f.write('Map<int, String> get86_zh_optimized() {\n  return {\n')
                  for phone, location in sorted(optimized_zh.items()):
                      f.write(f'    {phone}: "{location}",\n')
                  f.write('  };\n}\n')

              # 生成优化后的拼音版本
              with open('lib/phone_location_en_optimized.dart', 'w', encoding='utf-8') as f:
                 f.write('// Generated by GitHub Actions - Optimized Version\n')
                 f.write('// Source: https://github.com/dannyhu926/phone_location\n\n')
                 f.write('Map<int, String> get86_en_optimized() {\n  return {\n')
                 for phone, location in sorted(optimized_en.items()):
                    f.write(f'    {phone}: "{location}",\n')
                 f.write(' };\n}\n')

          if __name__ == "__main__":
               optimized_zh, optimized_en = optimize_phone_ranges('phone_location_processed.csv')
               generate_optimized_dart_files(optimized_zh, optimized_en)
           EOF
            python optimize_ranges.py

      - name: Commit and Push dart
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: "Update Dart phone location maps with optimized version"
           file_pattern: "lib/phone_location_*.dart"
           branch: dartnumber
           repository: .
           token: ${{ secrets.YOUR_GITHUB_TOKEN }}  
