name: Turkish Spam Numbers Weekly Data Processing

on:
  schedule:
    - cron: '0 13 * * 0' # Run every Sunday at 13:00 UTC
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: Turkish # Corrected branch name
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas
        run: pip install pandas

      - name: Download and Process Turkish Spam Numbers data
        run: |
          python <<EOF
          import pandas as pd

          try:
              # Directly download CSV data into a pandas DataFrame
              df = pd.read_csv('https://raw.githubusercontent.com/symbuzzer/Turkish-Spam-Numbers/main/numbers', header=None, names=['phoneNumber'], on_bad_lines='skip', dtype={'phoneNumber': str})
          except pd.errors.EmptyDataError:
              print("Error: CSV file is empty. Exiting.")
              exit(1)
          except pd.errors.ParserError as e:
              print(f"Error parsing CSV: {e}")
              exit(1)
          except Exception as e:
              print(f"Error downloading or processing CSV: {e}")
              exit(1)

          df['phoneNumber'] = df['phoneNumber'].astype(str).str.strip()
          df = df[df['phoneNumber'].notna() & (df['phoneNumber'] != '')]

          # The + sign should be preserved as we are directly reading the CSV
          df['labelId'] = 'spam-likely'
          df['name'] = ''
          df['avatar'] = ''
          df['isSubscribed'] = 1
          df['count'] = ''
          df['url'] = ''
          df = df[['phoneNumber', 'label', 'name', 'avatar', 'isSubscribed', 'count', 'url']]
          df.to_csv('processed_turkish_spam_numbers.csv', index=False)
          EOF

      - name: Commit and Push CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update processed Turkish Spam Numbers data"
          file_pattern: "processed_turkish_spam_numbers.csv"
          branch: Turkish # Corrected branch name
          repository: .
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
