name: US FCC database Daily Data Processing

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas and phonenumbers
        run: pip install pandas phonenumbers

      - name: Download and Process Data
        run: |
          mkdir -p original # Directory for raw download
          mkdir -p US       # Directory for processed files
          wget --content-disposition -O original/data.csv https://fccprod.servicenowservices.com/api/x_g_fmc_rmd/rmd/csv_download

          python <<EOF
          import pandas as pd
          import re
          import phonenumbers

          df = pd.read_csv('original/data.csv')
          df = df[['business_name', 'contact_telephone_number']]
          df = df.rename(columns={'business_name': 'name', 'contact_telephone_number': 'phoneNumber'})

          df['phoneNumber'] = df['phoneNumber'].astype(str).apply(lambda x: re.sub(r"^'+", "", x))
          df['phoneNumber'] = df['phoneNumber'].str.replace('.', '', regex=False)
          df['phoneNumber'] = df['phoneNumber'].str.strip()
          df['name'] = df['name'].str.replace(r'[",.]', '', regex=True)
          df['name'] = df['name'].str.replace(r'[\",.]', '', regex=True)
          df['name'] = df['name'].str.replace(r'[/]', '', regex=True)
          #df['name'] = df['name'].str.strip()

          def format_phone_number(number):
              try:
                  if number.startswith("+"):
                      parsed_number = phonenumbers.parse(number, None)
                      if phonenumbers.is_valid_number(parsed_number):
                          return phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                  else:
                      parsed_number = phonenumbers.parse(number, "US")
                      if phonenumbers.is_valid_number(parsed_number):
                          return phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.NATIONAL)
              except phonenumbers.phonenumberutil.NumberParseException:
                  pass
              return number

          df['phoneNumber'] = df['phoneNumber'].apply(format_phone_number)

          df = df[df['phoneNumber'].notna() & (df['phoneNumber'] != '')]  # Filter after formatting

          # 生成新格式数据
          #df['id'] = ''
          df['priority'] = 3
          df['action'] = 'block'
          df['labelId'] = 'telemarketing'
          df['isEnabled'] = 1
          df['isSubscribed'] = 1
          df['count'] = ''
          df['avatar'] = ''
          df['url'] = ''

          df = df[['name', 'priority', 'action', 'phoneNumber', 'labelId', 'isEnabled', 'isSubscribed', 'count', 'avatar', 'url']]
          df.to_csv('US/processed_v2.csv', index=False)
          
          # 保留原始格式
          df['label'] = 'Telemarketing'
          df['avatar'] = ''
          df['isSubscribed'] = 1
          df['count'] = ''
          df['url'] = ''
          df_legacy = df[['phoneNumber', 'label', 'name', 'avatar', 'isSubscribed', 'count', 'url']]
          df_legacy.to_csv('US/processed_data.csv', index=False)
          EOF

      - name: Commit Processed new CSVs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update US FCC processed CSV files"
          # file_pattern should match the location of the files relative to the repository root
          # Since 'checkout' checks out to the root, and we put files in 'US/' subdir:
          file_pattern: US/*.csv
          # 'repository: .' means the current repository, which is correct.
          # Use the GITHUB_TOKEN provided by Actions, not a custom secret unless necessary.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: specify the branch if it's different from the checked-out branch
          # However, since we checked out 'us', it will commit to 'us' by default.
          # push_options: --force # Use with caution if rewriting history is intended
