name: 合并固定电话和手机Merge Fixed Line and Mobile Data

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["合并fixed line优化0-9 末尾"]
    types:
      - completed

permissions:
  contents: write

jobs:
  merge-data:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dartnumber

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Create merged directory
        run: mkdir -p lib/cn/merged

      - name: Merge English Data
        run: |
          python << EOF
          import requests

          def download_and_extract(url):
              response = requests.get(url)
              response.raise_for_status()
              content = response.text
              # Find the start of the map data after "return {"
              start_index = content.find("return {") + len("return {")
              
              # Find the matching closing brace for the map
              brace_count = 1
              end_index = start_index
              while brace_count > 0 and end_index < len(content):
                  if content[end_index] == '{':
                      brace_count += 1
                  elif content[end_index] == '}':
                      brace_count -= 1
                  end_index += 1

              return content[start_index:end_index-1].strip()

          fixed_line_en_url = "https://raw.githubusercontent.com/haygcao/vccard/refs/heads/dartnumber/lib/merged/fixed_line_en.dart"
          mobile_en_url = "https://raw.githubusercontent.com/haygcao/vccard/refs/heads/dartnumber/lib/cn/phone_location_en_optimized.dart"

          fixed_line_en_data = download_and_extract(fixed_line_en_url)
          mobile_en_data = download_and_extract(mobile_en_url)

          # Merge data, ensuring fixed-line data comes first
          merged_en_content = f"{fixed_line_en_data}\n{mobile_en_data}"

          with open("lib/cn/merged/86_en.dart", "w", encoding="utf-8") as f:
              f.write(f"Map<int, String> get86_en() {{\n  return {{\n    {merged_en_content}\n  }};\n}}")
          EOF

      - name: Merge Chinese Data
        run: |
          python << EOF
          import requests

          def download_and_extract(url):
              response = requests.get(url)
              response.raise_for_status()
              content = response.text
              # Find the start of the map data after "return {"
              start_index = content.find("return {") + len("return {")
              
              # Find the matching closing brace for the map
              brace_count = 1
              end_index = start_index
              while brace_count > 0 and end_index < len(content):
                  if content[end_index] == '{':
                      brace_count += 1
                  elif content[end_index] == '}':
                      brace_count -= 1
                  end_index += 1

              return content[start_index:end_index-1].strip()

          fixed_line_zh_url = "https://raw.githubusercontent.com/haygcao/vccard/refs/heads/dartnumber/lib/merged/fixed_line_zh.dart"
          mobile_zh_url = "https://raw.githubusercontent.com/haygcao/vccard/refs/heads/dartnumber/lib/cn/phone_location_zh_optimized.dart"

          fixed_line_zh_data = download_and_extract(fixed_line_zh_url)
          mobile_zh_data = download_and_extract(mobile_zh_url)

          # Merge data, ensuring fixed-line data comes first
          merged_zh_content = f"{fixed_line_zh_data}\n{mobile_zh_data}"

          with open("lib/cn/merged/86_zh.dart", "w", encoding="utf-8") as f:
              f.write(f"Map<int, String> get86_zh() {{\n  return {{\n    {merged_zh_content}\n  }};\n}}")
          EOF

      - name: Commit and Push Merged Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Merge fixed-line and mobile phone location data into lib/cn/merged"
          file_pattern: "lib/cn/merged/86_*.dart"
          branch: dartnumber
          repository: .
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
